# Generated by Django 3.2 on 2023-04-20 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodIngData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 4, 20, 13, 16, 23, 73164))),
                ('unit_price', models.IntegerField()),
            ],
        ),
    ]
