# Generated by Django 3.2 on 2023-04-20 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20230420_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Egg',
            new_name='Eggs',
        ),
    ]
