# Generated by Django 3.2 on 2023-04-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_egg_eggs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
