# Generated by Django 3.2 on 2023-04-20 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_costs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eggs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 4, 20, 20, 10, 37, 862041))),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 4, 20, 20, 10, 37, 862041))),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Foods',
        ),
    ]
