# Generated by Django 3.2 on 2023-04-20 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_costs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='menu_name',
        ),
        migrations.AddField(
            model_name='foods',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 9, 58, 7, 98170)),
        ),
    ]
