# Generated by Django 3.2 on 2023-04-20 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_costs', '0002_auto_20230420_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 10, 0, 31, 557008)),
        ),
    ]
