# Generated by Django 3.2 on 2023-04-21 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_costs', '0027_auto_20230421_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pepper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 4, 21, 14, 23, 16, 677466))),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='eggs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 14, 23, 16, 677466)),
        ),
        migrations.AlterField(
            model_name='flour',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 14, 23, 16, 677466)),
        ),
        migrations.AlterField(
            model_name='sugar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 14, 23, 16, 677466)),
        ),
    ]
