# Generated by Django 3.2 on 2023-04-21 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_costs', '0030_auto_20230421_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchovy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 20, 1, 468018))),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SaltedMackerel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 20, 1, 468018))),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SaltedShrimp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 20, 1, 468018))),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Squid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 20, 1, 468018))),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='eggs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 20, 1, 452396)),
        ),
        migrations.AlterField(
            model_name='flour',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 20, 1, 468018)),
        ),
        migrations.AlterField(
            model_name='pepper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 20, 1, 468018)),
        ),
        migrations.AlterField(
            model_name='sugar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 20, 1, 468018)),
        ),
    ]
