# Generated by Django 3.2 on 2023-04-21 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_costs', '0031_auto_20230421_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapRice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 44, 16, 562863))),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RedBeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 44, 16, 562863))),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 44, 16, 562863))),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WhiteBeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 44, 16, 562863))),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='anchovy',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 44, 16, 562863)),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 44, 16, 547242)),
        ),
        migrations.AlterField(
            model_name='flour',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 44, 16, 547242)),
        ),
        migrations.AlterField(
            model_name='pepper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 44, 16, 562863)),
        ),
        migrations.AlterField(
            model_name='saltedmackerel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 44, 16, 562863)),
        ),
        migrations.AlterField(
            model_name='saltedshrimp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 44, 16, 562863)),
        ),
        migrations.AlterField(
            model_name='squid',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 44, 16, 562863)),
        ),
        migrations.AlterField(
            model_name='sugar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 44, 16, 562863)),
        ),
    ]
