# Generated by Django 3.2 on 2023-04-24 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_costs', '0035_auto_20230424_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchovy',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 21, 34, 41, 931544)),
        ),
        migrations.AlterField(
            model_name='chaprice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 21, 34, 41, 947166)),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 21, 34, 41, 931544)),
        ),
        migrations.AlterField(
            model_name='flour',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 21, 34, 41, 931544)),
        ),
        migrations.AlterField(
            model_name='pepper',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 21, 34, 41, 931544)),
        ),
        migrations.AlterField(
            model_name='redbeans',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 21, 34, 41, 947166)),
        ),
        migrations.AlterField(
            model_name='rice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 21, 34, 41, 931544)),
        ),
        migrations.AlterField(
            model_name='saltedmackerel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 21, 34, 41, 931544)),
        ),
        migrations.AlterField(
            model_name='saltedshrimp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 21, 34, 41, 931544)),
        ),
        migrations.AlterField(
            model_name='squid',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 21, 34, 41, 931544)),
        ),
        migrations.AlterField(
            model_name='sugar',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 21, 34, 41, 931544)),
        ),
        migrations.AlterField(
            model_name='whitebeans',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 21, 34, 41, 947166)),
        ),
    ]
